// <auto-generated> Generated by VALYR (Unity) </auto-generated>
using UnityEngine;
using System;
using Core.Configs;
using Unity.Interfaces;

namespace Unity.GeneratedConfigs
{
    [CreateAssetMenu(fileName = "AntiRollBarModuleConfig", menuName = "VALYR/Configs/AntiRollBarModule")]
    public class AntiRollBarModuleConfig : ScriptableObject, IModuleConfigAsset
    {
        public Core.Modules.AntiRollBarModule.Config data = new Core.Modules.AntiRollBarModule.Config();

        // Interface Implementation
        public ModuleConfig GetConfig() => data;
        public Type GetTargetModuleType() => typeof(Core.Modules.AntiRollBarModule);
    }
}
