// <auto-generated> Generated by VALYR (Unity) </auto-generated>
using UnityEngine;
using System;
using Core.Configs;
using Unity.Interfaces;

namespace Unity.GeneratedConfigs
{
    [CreateAssetMenu(fileName = "DrivingAssistsModuleConfig", menuName = "VALYR/Configs/DrivingAssistsModule")]
    public class DrivingAssistsModuleConfig : ScriptableObject, IModuleConfigAsset
    {
        public Core.Modules.DrivingAssistsModule.Config data = new Core.Modules.DrivingAssistsModule.Config();

        // Interface Implementation
        public ModuleConfig GetConfig() => data;
        public Type GetTargetModuleType() => typeof(Core.Modules.DrivingAssistsModule);
    }
}
