// <auto-generated> Generated by VALYR (Unity) </auto-generated>
using UnityEngine;
using System;
using Core.Configs;
using Unity.Interfaces;

namespace Unity.GeneratedConfigs
{
    [CreateAssetMenu(fileName = "DrivetrainModuleConfig", menuName = "VALYR/Configs/DrivetrainModule")]
    public class DrivetrainModuleConfig : ScriptableObject, IModuleConfigAsset
    {
        public Core.Modules.DrivetrainModule.Config data = new Core.Modules.DrivetrainModule.Config();

        // Interface Implementation
        public ModuleConfig GetConfig() => data;
        public Type GetTargetModuleType() => typeof(Core.Modules.DrivetrainModule);
    }
}
