// <auto-generated> Generated by VALYR (Unity) </auto-generated>
using UnityEngine;
using System;
using Core.Configs;
using Unity.Interfaces;

namespace Unity.GeneratedConfigs
{
    [CreateAssetMenu(fileName = "EngineModuleConfig", menuName = "VALYR/Configs/EngineModule")]
    public class EngineModuleConfig : ScriptableObject, IModuleConfigAsset
    {
        public Core.Modules.EngineModule.Config data = new Core.Modules.EngineModule.Config();

        // Interface Implementation
        public ModuleConfig GetConfig() => data;
        public Type GetTargetModuleType() => typeof(Core.Modules.EngineModule);
    }
}
