// <auto-generated> Generated by VALYR (Unity) </auto-generated>
using UnityEngine;
using System;
using Core.Configs;
using Unity.Interfaces;

namespace Unity.GeneratedConfigs
{
    [CreateAssetMenu(fileName = "GearboxModuleConfig", menuName = "VALYR/Configs/GearboxModule")]
    public class GearboxModuleConfig : ScriptableObject, IModuleConfigAsset
    {
        public Core.Modules.GearboxModule.Config data = new Core.Modules.GearboxModule.Config();

        // Interface Implementation
        public ModuleConfig GetConfig() => data;
        public Type GetTargetModuleType() => typeof(Core.Modules.GearboxModule);
    }
}
