// <auto-generated> Generated by VALYR (Unity) </auto-generated>
using UnityEngine;
using System;
using Core.Configs;
using Unity.Interfaces;

namespace Unity.GeneratedConfigs
{
    [CreateAssetMenu(fileName = "SteeringModuleConfig", menuName = "VALYR/Configs/SteeringModule")]
    public class SteeringModuleConfig : ScriptableObject, IModuleConfigAsset
    {
        public Core.Modules.SteeringModule.Config data = new Core.Modules.SteeringModule.Config();

        // Interface Implementation
        public ModuleConfig GetConfig() => data;
        public Type GetTargetModuleType() => typeof(Core.Modules.SteeringModule);
    }
}
