// <auto-generated> Generated by VALYR (Unity) </auto-generated>
using UnityEngine;
using System;
using Core.Configs;
using Unity.Interfaces;

namespace Unity.GeneratedConfigs
{
    [CreateAssetMenu(fileName = "SuspensionModuleConfig", menuName = "VALYR/Configs/SuspensionModule")]
    public class SuspensionModuleConfig : ScriptableObject, IModuleConfigAsset
    {
        public Core.Modules.SuspensionModule.Config data = new Core.Modules.SuspensionModule.Config();

        // Interface Implementation
        public ModuleConfig GetConfig() => data;
        public Type GetTargetModuleType() => typeof(Core.Modules.SuspensionModule);
    }
}
