// <auto-generated> Generated by VALYR (Unity) </auto-generated>
using UnityEngine;
using System;
using Core.Configs;
using Unity.Interfaces;

namespace Unity.GeneratedConfigs
{
    [CreateAssetMenu(fileName = "TireModuleConfig", menuName = "VALYR/Configs/TireModule")]
    public class TireModuleConfig : ScriptableObject, IModuleConfigAsset
    {
        public Core.Modules.TireModule.Config data = new Core.Modules.TireModule.Config();

        // Interface Implementation
        public ModuleConfig GetConfig() => data;
        public Type GetTargetModuleType() => typeof(Core.Modules.TireModule);
    }
}
