// <auto-generated> Generated by VALYR (Unity) </auto-generated>
using UnityEngine;
using System;
using Core.Configs;
using Unity.Interfaces;

namespace Unity.GeneratedConfigs
{
    [CreateAssetMenu(fileName = "WheelContactModuleConfig", menuName = "VALYR/Configs/WheelContactModule")]
    public class WheelContactModuleConfig : ScriptableObject, IModuleConfigAsset
    {
        public Core.Modules.WheelContactModule.Config data = new Core.Modules.WheelContactModule.Config();

        // Interface Implementation
        public ModuleConfig GetConfig() => data;
        public Type GetTargetModuleType() => typeof(Core.Modules.WheelContactModule);
    }
}
