using System;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using Core.Configs;
using UnityEditor;
using UnityEngine;

namespace Editor
{
    public static class ModuleConfigGenerator
    {
        private const string OutputPath = "Assets/Scripts/Unity/GeneratedConfigs";

        [MenuItem("VALYR/Generate Config Assets")]
        public static void Generate()
        {
            if (!Directory.Exists(OutputPath)) Directory.CreateDirectory(OutputPath);

            // Находим все классы конфигов
            var configTypes = Assembly.GetAssembly(typeof(ModuleConfig))
                .GetTypes()
                .Where(t => t.IsClass && !t.IsAbstract && t.IsSubclassOf(typeof(ModuleConfig)))
                .ToList();

            foreach (var type in configTypes) GenerateScript(type);

            AssetDatabase.Refresh();
            Debug.Log($"Generated {configTypes.Count} config wrappers.");
        }

        private static void GenerateScript(Type configType)
        {
            string typeName;
            string menuName;
            string configFullType;
            string targetModuleType;

            if (configType.IsNested && configType.DeclaringType != null)
            {
                var moduleName = configType.DeclaringType.Name;
                typeName = $"{moduleName}Config";
                menuName = $"VALYR/Configs/{moduleName}";
                configFullType = $"{configType.DeclaringType.Namespace}.{moduleName}.Config";
                targetModuleType = $"{configType.DeclaringType.Namespace}.{moduleName}";
            }
            else
            {
                typeName = $"{configType.Name}Asset";
                menuName = $"VALYR/Configs/{configType.Name}";
                configFullType = $"{configType.Namespace}.{configType.Name}";
                targetModuleType = "null";
            }

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated> Generated by VALYR (Unity) </auto-generated>");
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine("using System;");
            sb.AppendLine("using Core.Configs;");
            sb.AppendLine("using Unity.Interfaces;");

            sb.AppendLine();
            sb.AppendLine("namespace Unity.GeneratedConfigs");
            sb.AppendLine("{");
            sb.AppendLine($"    [CreateAssetMenu(fileName = \"{typeName}\", menuName = \"{menuName}\")]");
            sb.AppendLine($"    public class {typeName} : ScriptableObject, IModuleConfigAsset");
            sb.AppendLine("    {");
            sb.AppendLine($"        public {configFullType} data = new {configFullType}();");
            sb.AppendLine();
            sb.AppendLine("        // Interface Implementation");
            sb.AppendLine("        public ModuleConfig GetConfig() => data;");
            sb.AppendLine($"        public Type GetTargetModuleType() => typeof({targetModuleType});");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            File.WriteAllText(Path.Combine(OutputPath, $"{typeName}.cs"), sb.ToString());
        }
    }
}